import type { Database } from "../client.js";
import * as schema from "../schema/index.js";

/** Complete portable account export, excluding credentials and session secrets. */
export async function exportAccountData(db: Database, userId: string) {
  const [
    users,
    connectedEmailAccounts,
    emailThreads,
    emailMessages,
    normalizedEmails,
    emailAttachments,
    classifierVersions,
    classificationResults,
    extractedEntities,
    companies,
    companyAliases,
    roles,
    applications,
    applicationEvents,
    applicationMatchCandidates,
    userCorrections,
    reviewQueueItems,
    notifications,
    auditLog,
    userSettings,
    analyticsSites,
    analyticsSessions,
    analyticsEvents,
    correlationPredictions,
    correlationFeatures,
  ] = await Promise.all([
    db
      .select({
        id: schema.users.id,
        email: schema.users.email,
        role: schema.users.role,
        createdAt: schema.users.createdAt,
        updatedAt: schema.users.updatedAt,
      })
      .from(schema.users),
    db.select().from(schema.connectedEmailAccounts),
    db.select().from(schema.emailThreads),
    db.select().from(schema.emailMessages),
    db.select().from(schema.normalizedEmails),
    db.select().from(schema.emailAttachments),
    db.select().from(schema.classifierVersions),
    db.select().from(schema.classificationResults),
    db.select().from(schema.extractedEntities),
    db.select().from(schema.companies),
    db.select().from(schema.companyAliases),
    db.select().from(schema.roles),
    db.select().from(schema.applications),
    db.select().from(schema.applicationEvents),
    db.select().from(schema.applicationMatchCandidates),
    db.select().from(schema.userCorrections),
    db.select().from(schema.reviewQueueItems),
    db.select().from(schema.notifications),
    db.select().from(schema.auditLog),
    db.select().from(schema.userSettings),
    db.select().from(schema.analyticsSites),
    db.select().from(schema.analyticsSessions),
    db.select().from(schema.analyticsEvents),
    db.select().from(schema.correlationPredictions),
    db.select().from(schema.correlationFeatures),
  ]);
  return {
    format: "apptrack-export-v1",
    exportedAt: new Date().toISOString(),
    userId,
    data: {
      users,
      connectedEmailAccounts,
      emailThreads,
      emailMessages,
      normalizedEmails,
      emailAttachments,
      classifierVersions,
      classificationResults,
      extractedEntities,
      companies,
      companyAliases,
      roles,
      applications,
      applicationEvents,
      applicationMatchCandidates,
      userCorrections,
      reviewQueueItems,
      notifications,
      auditLog,
      userSettings,
      analyticsSites,
      analyticsSessions,
      analyticsEvents,
      correlationPredictions,
      correlationFeatures,
    },
  };
}
